spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\\Users\\krzuc\\OneDrive\\Dokumenty\\java_training\\Udemi_Spring\\todo-app\\todo.db'
  jpa.hibernate.ddl-auto: create-drop
  my.prop: 'test'
