spring:
  flyway:
    baseline-on-migrate: true
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\\Users\\krzuc\\OneDrive\\Dokumenty\\java_training\\Udemi_Spring\\todo-app\\todo.db'
  jpa.hibernate.ddl-auto: validate
  management:
    endpoint:
      info:
        enabled=true:
      env:
        enabled=true:
    endpoints:
      web:
        exposure:
          include: '*'
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'TodoApp'
  resource: 'todo-spring-client'
  public-client: true


